name: Release Next
on:
  repository_dispatch:
    types: [next]
  workflow_dispatch:

env:
  DOCUMENTATION_PUBLISH_REPO: ${{ github.repository_owner }}/${{ github.repository_owner }}.github.io
  DOCUMENTATION_PUBLISH_BRANCH: master
  DOCUMENTATION_PUBLISH_FOLDER: uikit/next
  DOCUMENTATION_PUBLISH_MESSAGE: "docs: storybook for next of ${{ github.repository }}"
  DOCUMENTATION_URL: https://${{ github.repository_owner }}.github.io/uikit/next/

jobs:
  Release:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: production
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CHECKOUT_REF: ${{ github.event.client_payload.ref }}
      RELEASE_TYPE: ${{ github.event.client_payload.type }}

    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v2
        with:
          # Pulls all commits (needed for semantic release to correctly version)
          # See https://github.com/semantic-release/semantic-release/issues/1526
          fetch-depth: "0"

      # Pulls all tags (needed for semantic release to correctly version)
      - name: Fetch git tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*

      - name: Install
        env:
          # ensure dev dependencies are installed
          NODE_ENV: development
        run: npm ci

      - name: Bootstrap
        env:
          # ensure dev dependencies are installed
          NODE_ENV: development
        run: npm run bootstrap

      - name: Publish Setup
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      - name: Publish (Lerna)
        env:
          NODE_AUTH_TOKEN: ${{secrets.HV_NPM_AUTOMATION_TOKEN}}
        run: |
          npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npx lerna publish prerelease  --yes --no-git-reset --preid next --dist-tag next