name: Security CodeDx and BlackDuck Scans
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily at 03:00
  repository_dispatch:
    types: [master]

env:
  CODEDX_SERVER_PROJECT_ID: 120
  DEP_CHECK_TOOL_VERSION: 6.5.3
  BLACKDUCK_VERSION: 7

jobs:
  CodeDxScan:
    name: CodeDx Scan
    runs-on: [self-hosted, Linux]

    steps:
      - name: Discover current branch
        run: |
          REF=$( echo "${{ github.ref }}" ) # gets the branch or tag ref that triggered the workflow (something like 'refs/heads/branch-name')
          REF=$( echo ${REF^^} ) # sets it to uppercase
          REF=$( echo ${REF##*/} ) # removes the 'refs/heads/' reference
          REF=$( echo ${REF//[_]/-} ) # replaces any '_' for a '-'
          echo "CURRENT_BRANCH=$REF" >> $GITHUB_ENV
          
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Setup dependency-check
        uses: ./.github/setup-dependency-check
        with:
          version: ${{env.DEP_CHECK_TOOL_VERSION}}

      - name: Get uikit dependencies
        run: |
          npm ci
          npm run bootstrap
      - name: Get applitools dependencies
        run: |
          cd automation/applitools
          npm ci
      - name: Get pa11y dependencies
        run: |
          cd automation/pa11y
          npm ci

      - name: Run dependency check
        run: |
          dependency-check.sh \
            --disableArchive \
            --disableAssembly \
            --disableJar \
            --project "uikit" \
            --format XML \
            --scan . \
            --out .
        continue-on-error: true

      - name: Trigger Analysis and check results
        uses: ./.github/codedx-analysis
        with:
          file: dependency-check-report.xml
          serverUrl: ${{ secrets.CODEDX_SERVER_URL }}
          projectId: '${{ env.CODEDX_SERVER_PROJECT_ID }};branch=${{ env.CURRENT_BRANCH }}'
          key: ${{ secrets.CODEDX_TOKEN }}

  BlackDuckScan:
    name: BlackDuck Scan
    runs-on: [self-hosted, Linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"

      - name: Build uikit
        run: |
          npm ci
          npm run bootstrap
          npm run build

      - name: Run BlackDuck Scan
        env:
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_SERVER_URL }}
          BLACKDUCK_TOKEN: ${{ secrets.BLACKDUCK_TOKEN }}
        run: ./.github/component-scans/blackduck-check.sh
