name: Pa11y Tests

on:
  workflow_dispatch:
    branches:
      - master
      - "next*"
  workflow_call:

jobs:
  run-tests:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        uses: ./.github/actions/install-dependencies

      - name: Build Documentation
        uses: ./.github/actions/build-documentation
        if: github.event_name == 'workflow_dispatch'

      - name: Fetch Documentation
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: ${{ github.workspace }}/dist

      - name: Run Tests
        run: |
          npx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
          "npx http-server dist --port 6006 --silent" \
          "npx wait-on tcp:6006 && npm run test:pa11y"